hal: renesas: Add sleep code
zephyrproject-rtos/hal_renesas pull request #14
Opened 2024-03-20 15:12 UTC by kasjer

This adds startup code that handles wakeup from deep sleep (CPU-off)

da1469x_sleep() function is intended to be called from OS function that wants to go to sleep.
When function finishes basic system functionality is restored if system went to sleep (clocks, GPIO etc.).

Function da1469x_sleep_config() should be called during startup to configure PDC entries needed for wakeup functionality.

2024-03-25 10:37 UTC, gmarull requested changes
please, no zephyr glue code in HALs, this is a bad practice.

2024-03-25 13:28 UTC, kasjer commented
while there was no Zephyr code in hal some includes were pulled from zephyr tree for asm macros, now it's removed

2024-04-02 08:42 UTC, blauret approved these changes

2024-04-09 23:34 UTC, andrzej-kaczmarek approved these changes

2024-04-09 23:34 UTC, merged