Support RA6 RA4 RA2 hal layer
zephyrproject-rtos/hal_renesas pull request #26
Opened 2024-07-09 06:25 UTC by duynguyenxa

This PR is a draft version to support the following feature on hal_renesas:
BSP support:
RA2A1
RA2L1
RA4M1
RA4M2
RA4M3
RA4E1
RA4E2
RA4W1
RA6M1
RA6M2
RA6M3
RA6M4
RA6M5
RA6E1
RA6E2

Module:
SCI UART 

This is only now a draft version for architecture approach method of Renesas RA hal layer support.
We would like to receive review and feedback from community member on this

2024-07-14 07:09 UTC, soburi requested changes

2024-07-14 07:09 UTC, soburi commented on drivers/ra/fsp/src/r_sci_uart/r_sci_uart.c
> +        transfer_info_t * p_info = p_cfg->p_transfer_rx->p_cfg->p_info;
This line is not in FSP v5.3.0.
Please describe why added this line.

We will need to update the base version in the future.
Changes from a baseline version should be tracked as separate commits.

2024-07-14 07:09 UTC, soburi commented on drivers/ra/fsp/src/bsp/cmsis/Device/RENESAS/Include/R7FA4E2B9.h
Some files seem to be different from those in FSP v5.3.0.
It would be a good idea to split these into separate commits and explain why they are different, if necessary.
This would make future management more difficult.

2024-08-02 11:03 UTC, soburi commented
@duynguyenxa 

(Move from https://github.com/zephyrproject-rtos/zephyr/pull/76081#issuecomment-2265097353)

The CMSIS header has a difference with v5.3.0.
If it is not required at this time, I think it is good to use the v5.3.0 version.
And this PR has the same modification for the SCI driver for SCI-B in https://github.com/zephyrproject-rtos/hal_renesas/pull/24#issuecomment-2264840378.

Let's record this as well.

And this PR has no other problems.

2024-08-05 07:19 UTC, duynguyenxa commented
> @duynguyenxa
> 
> (Move from [zephyrproject-rtos/zephyr#76081 (comment)](https://github.com/zephyrproject-rtos/zephyr/pull/76081#issuecomment-2265097353))
> 
> The CMSIS header has a difference with v5.3.0. If it is not required at this time, I think it is good to use the v5.3.0 version. And this PR has the same modification for the SCI driver for SCI-B in [#24 (comment)](https://github.com/zephyrproject-rtos/hal_renesas/pull/24#issuecomment-2264840378).
> 
> Let's record this as well.
> 
> And this PR has no other problems.

@soburi , @ydamigos , @thaoluonguw , @KhiemNguyenT  all items are updated

2024-08-05 07:32 UTC, soburi commented
R7FA4E2B9.h
R7FA4M1AB.h
R7FA4M2AD.h
R7FA4M3AF.h
R7FA4W1AD.h

These are still seems to difference with v5.3.0.
If required the diffs, please log, or if it is no needed, I think it is easy to maintain to leave same with v5.3.0.

2024-08-05 07:48 UTC, soburi commented
```
Files drivers/ra/fsp/src/bsp/cmsis/Device/RENESAS/Include/R7FA4M2AD.h and /home/tokita/fsp/ra/fsp/src/bsp/cmsis/Device/RENESAS/Include/R7FA4M2AD.h differ
Files drivers/ra/fsp/src/bsp/cmsis/Device/RENESAS/Include/R7FA4M3AF.h and /home/tokita/fsp/ra/fsp/src/bsp/cmsis/Device/RENESAS/Include/R7FA4M3AF.h differ
```

Just two more!

2024-08-05 07:48 UTC, duynguyenxa commented
> R7FA4E2B9.h R7FA4M1AB.h R7FA4M2AD.h R7FA4M3AF.h R7FA4W1AD.h
> 
> These are still seems to difference with v5.3.0. If required the diffs, please log, or if it is no needed, I think it is easy to maintain to leave same with v5.3.0.

Sorry I push the wrong  it's OK now please help to recheck

> R7FA4E2B9.h R7FA4M1AB.h R7FA4M2AD.h R7FA4M3AF.h R7FA4W1AD.h
> 
> These are still seems to difference with v5.3.0. If required the diffs, please log, or if it is no needed, I think it is easy to maintain to leave same with v5.3.0.

@soburi , Sorry I mistakenly push only the patch, please help to recheck again

2024-08-05 07:53 UTC, soburi commented
> > R7FA4E2B9.h R7FA4M1AB.h R7FA4M2AD.h R7FA4M3AF.h R7FA4W1AD.h
> > These are still seems to difference with v5.3.0. If required the diffs, please log, or if it is no needed, I think it is easy to maintain to leave same with v5.3.0.
> 
> Sorry I push the wrong it's OK now please help to recheck
> 
> > R7FA4E2B9.h R7FA4M1AB.h R7FA4M2AD.h R7FA4M3AF.h R7FA4W1AD.h
> > These are still seems to difference with v5.3.0. If required the diffs, please log, or if it is no needed, I think it is easy to maintain to leave same with v5.3.0.
> 
> @soburi , Sorry I mistakenly push only the patch, please help to recheck again

https://github.com/zephyrproject-rtos/hal_renesas/pull/26#issuecomment-2268400585

2024-08-05 07:54 UTC, duynguyenxa commented
> > R7FA4E2B9.h R7FA4M1AB.h R7FA4M2AD.h R7FA4M3AF.h R7FA4W1AD.h
> > These are still seems to difference with v5.3.0. If required the diffs, please log, or if it is no needed, I think it is easy to maintain to leave same with v5.3.0.
> 
> Sorry I push the wrong it's OK now please help to recheck
> 
> > R7FA4E2B9.h R7FA4M1AB.h R7FA4M2AD.h R7FA4M3AF.h R7FA4W1AD.h
> > These are still seems to difference with v5.3.0. If required the diffs, please log, or if it is no needed, I think it is easy to maintain to leave same with v5.3.0.
> 
> @soburi , Sorry I mistakenly push only the patch note, please help to recheck again

2024-08-05 07:56 UTC, soburi approved these changes
LGTM

2024-08-05 07:57 UTC, soburi commented
> > > R7FA4E2B9.h R7FA4M1AB.h R7FA4M2AD.h R7FA4M3AF.h R7FA4W1AD.h
> > > These are still seems to difference with v5.3.0. If required the diffs, please log, or if it is no needed, I think it is easy to maintain to leave same with v5.3.0.
> > 
> > 
> > Sorry I push the wrong it's OK now please help to recheck
> > > R7FA4E2B9.h R7FA4M1AB.h R7FA4M2AD.h R7FA4M3AF.h R7FA4W1AD.h
> > > These are still seems to difference with v5.3.0. If required the diffs, please log, or if it is no needed, I think it is easy to maintain to leave same with v5.3.0.
> > 
> > 
> > @soburi , Sorry I mistakenly push only the patch note, please help to recheck again

Oops, sorry.

2024-08-05 07:57 UTC, duynguyenxa commented
> > > R7FA4E2B9.h R7FA4M1AB.h R7FA4M2AD.h R7FA4M3AF.h R7FA4W1AD.h
> > > These are still seems to difference with v5.3.0. If required the diffs, please log, or if it is no needed, I think it is easy to maintain to leave same with v5.3.0.
> > 
> > 
> > Sorry I push the wrong it's OK now please help to recheck
> > > R7FA4E2B9.h R7FA4M1AB.h R7FA4M2AD.h R7FA4M3AF.h R7FA4W1AD.h
> > > These are still seems to difference with v5.3.0. If required the diffs, please log, or if it is no needed, I think it is easy to maintain to leave same with v5.3.0.
> > 
> > 
> > @soburi , Sorry I mistakenly push only the patch, please help to recheck again
> 
> [#26 (comment)](https://github.com/zephyrproject-rtos/hal_renesas/pull/26#issuecomment-2268400585)

It's fixed at https://github.com/zephyrproject-rtos/hal_renesas/compare/8abb13d81d5f0bfd6db882296cbc66c5feea5286..795b884f504ab742ac3886f7d2c3e73d69bee0cb

2024-08-05 08:02 UTC, soburi commented
@ydamigos @KhiemNguyenT 
Could you take a look, please?

2024-08-07 02:25 UTC, soburi commented
@ydamigos @KhiemNguyenT

Could you progress this a bit? 
The SCI_UART will be available if this PR and #71174 merge, some boards will be able to merge.

2024-08-07 07:41 UTC, thaoluonguw commented
I am OK with these updates. Thank you.

2024-08-07 07:48 UTC, KhiemNguyenT approved these changes

2024-08-07 07:48 UTC, merged