Initial support for ADC hal
zephyrproject-rtos/hal_renesas pull request #27
Opened 2024-07-20 04:56 UTC by duynguyenxa

This PR add ADC driver to hal_renesas

2024-07-22 07:09 UTC, ydamigos commented
@thaoluonguw Could you please check it? I can't add you as a reviewer.

2024-07-30 01:39 UTC, soburi requested changes

2024-07-30 01:39 UTC, soburi commented on zephyr/ra/ra_cfg/fsp_cfg/r_adc_cfg.h
> +/* generated configuration header file - do not edit */
Please clarify the license and author.

2024-07-31 13:51 UTC, ydamigos approved these changes

2024-08-01 08:10 UTC, thaoluonguw commented on zephyr/ra/ra_cfg/fsp_cfg/r_adc_cfg.h
> +/* generated configuration header file - do not edit */
We updated. Thanks for your feedback.

2024-08-01 16:14 UTC, thaoluonguw approved these changes

2024-08-01 21:21 UTC, soburi commented
BTW, it seems that the source code for this FSP is different from what has been made public. How should people other than those at Renesas review it?

Ideally, the sources stored in this repository should be the same as the upstream FSP sources. If you are including future releases, it would be easier for me to check if you could also submit them to FSP as a PR at the same time.
Proper management of differences is also important for providing feedback to upstream.

(Since you've the FSP switched to BSD-3, you might as well do it the open-source way.)

2024-08-01 21:27 UTC, soburi approved these changes
The zephyr part is OK.
The FSP part probably contains code that is unreleased, so it's difficult for me to judge. (I think it's probably OK though.)

2024-08-02 01:12 UTC, KhiemNguyenT commented
> The zephyr part is OK. The FSP part probably contains code that is unreleased, so it's difficult for me to judge. (I think it's probably OK though.)

@duynguyenxa , please give an explanation for the diff.

2024-08-02 03:46 UTC, duynguyenxa commented
> The zephyr part is OK. The FSP part probably contains code that is unreleased, so it's difficult for me to judge. (I think it's probably OK though.)

@soburi , this is a snapshot of FSP at release 5.3.0, are compare with 5.3.0 or the latest version on Renesas github (5.4.0)

2024-08-02 04:07 UTC, soburi commented
@duynguyenxa @KhiemNguyenT 
> > The zephyr part is OK. The FSP part probably contains code that is unreleased, so it's difficult for me to judge. (I think it's probably OK though.)
> 
> @soburi , this is a snapshot of FSP at release 5.3.0, are you compare with FSP v5.3.0 or the latest version on Renesas github (v5.4.0)

If that is the case, there will be a discrepancy because the currently installed RA8M1 and SCI-B drivers are v5.3.0. This may not be a problem in general, but it will be a chimera, which is not desirable from a management perspective.
My only concern is the increased management effort, which is not a problem as long as it does not create a huge burden.

2024-08-02 04:33 UTC, KhiemNguyenT commented
> @duynguyenxa @KhiemNguyenT
> 
> > > The zephyr part is OK. The FSP part probably contains code that is unreleased, so it's difficult for me to judge. (I think it's probably OK though.)
> > 
> > 
> > @soburi , this is a snapshot of FSP at release 5.3.0, are you compare with FSP v5.3.0 or the latest version on Renesas github (v5.4.0)
> 
> If that is the case, there will be a discrepancy because the currently installed RA8M1 and SCI-B drivers are v5.3.0. This may not be a problem in general, but it will be a chimera, which is not desirable from a management perspective. My only concern is the increased management effort, which is not a problem as long as it does not create a huge burden.

@soburi , this is the open-source development, then we may relax the policy. In general, we try to keep sync with latest FSP HAL, but it's not the mandatory condition to accept the PRs. e.g. we will not wait for new FSP release in order to start some development.
In case there's a diff which leads to some issues, a PR will be submitted. Does it make sense ?

2024-08-02 04:56 UTC, soburi commented
@KhiemNguyenT 

Yes , I think it make a sense.

Rather than the need to synchronize, I think it is necessary to manage the differences with the upstream (we need to know and manage what version we are used, and what chagen we maked).
The simple problem is that when an unpublished change is presented here, it can be hard to tell whether it's something that will merge upstream in the future, or whether it's something specific to the Zephyr repository.
I think that if a PR is made to upstream, this will be easier to manage.
I'm not to say that you shouldn't use the latest version.

2024-08-02 06:45 UTC, ydamigos commented
@KhiemNguyenT PR has three approvals. Should you merge it? If yes, we should remove draft label from PR #76127.

2024-08-02 07:30 UTC, merged