hal: renesas: rz: Initial support for IPM
zephyrproject-rtos/hal_renesas pull request #61
Opened 2024-12-13 06:48 UTC by nhutnguyenkc

Initial HAL support for IPM

2024-12-23 05:03 UTC, thaoluonguw approved these changes
It looks good to me.

2024-12-23 06:33 UTC, duynguyenxa requested changes

2024-12-24 06:38 UTC, nhutnguyenkc commented on zephyr/rz/rz_cfg/fsp_cfg/rzg/r_mhu_ns_cfg.h
> +      #endif
I have fixed the alignment. Please help me check again.

2024-12-24 06:38 UTC, nhutnguyenkc commented on zephyr/rz/rz_cfg/fsp_cfg/rzg/r_mhu_ns_cfg.h
> +      #endif
@duynguyenxa , I have fixed the alignment. Please help me check again.

2024-12-24 06:40 UTC, duynguyenxa approved these changes

2024-12-24 06:50 UTC, KhiemNguyenT approved these changes

2024-12-24 08:52 UTC, merged